apiVersion: v1
kind: ServiceAccount
metadata:
  name: spy-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: spy-role
rules:
  # 💡 ノードのラベル（静的情報）を読み取るための権限
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  # 💡 ノードの現在のリソース使用量（動的情報）をMetrics Serverから読み取るための権限
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spy-rb
subjects:
  - kind: ServiceAccount
    name: spy-service-account
roleRef:
  kind: ClusterRole
  name: spy-role
  apiGroup: rbac.authorization.k8s.io