FROM python:3.9-slim

# コンテナのタイムゾーンや基本設定
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

# NDNライブラリとKubernetes操作用ライブラリのインストール
RUN pip install --no-cache-dir python-ndn kubernetes

# プログラムのコピー
COPY ndn_manager.py /app/

# Managerの起動
CMD ["python", "ndn_manager.py"]